version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://163.123.183.82:18913/swd392?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=CqoKYZxz
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=CqoKYZxz
    ports:
      - "18913:18913"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
